services:
  - type: web
    name: bc-platform
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app --timeout 120 --workers 1
    envVars:
      - key: FLASK_APP
        value: run.py
      - key: SECRET_KEY
        value: bc-platform-secret-key-2024
      - - key: DATABASE_URL
      sync: false