"""add pathway table

Revision ID: 263f31035557
Revises: f656acbd49f2
Create Date: 2026-07-18 11:08:06.061794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '263f31035557'
down_revision = 'f656acbd49f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pathway',
    sa.Column('pathway_id', sa.Integer(), nullable=False),
    sa.Column('gene_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('external_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['gene_id'], ['gene.gene_id'], ),
    sa.PrimaryKeyConstraint('pathway_id')
    )
    with op.batch_alter_table('pathway', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pathway_gene_id'), ['gene_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pathway', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pathway_gene_id'))

    op.drop_table('pathway')
    # ### end Alembic commands ###
