"""add mutation model

Revision ID: 3d14da4ef29c
Revises: 50d0e1556849
Create Date: 2026-07-17 21:22:12.932301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d14da4ef29c'
down_revision = '50d0e1556849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mutation',
    sa.Column('mutation_id', sa.Integer(), nullable=False),
    sa.Column('gene_id', sa.Integer(), nullable=False),
    sa.Column('hgvs_c', sa.String(length=255), nullable=True),
    sa.Column('hgvs_p', sa.String(length=255), nullable=True),
    sa.Column('mutation_type', sa.String(length=50), nullable=True),
    sa.Column('clinical_significance', sa.String(length=100), nullable=True),
    sa.Column('chromosome', sa.String(length=10), nullable=True),
    sa.Column('position', sa.BigInteger(), nullable=True),
    sa.Column('ref_allele', sa.String(length=50), nullable=True),
    sa.Column('alt_allele', sa.String(length=50), nullable=True),
    sa.Column('clinvar_id', sa.String(length=30), nullable=True),
    sa.Column('cosmic_id', sa.String(length=30), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['gene_id'], ['gene.gene_id'], ),
    sa.PrimaryKeyConstraint('mutation_id')
    )
    with op.batch_alter_table('mutation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mutation_gene_id'), ['gene_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mutation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mutation_gene_id'))

    op.drop_table('mutation')
    # ### end Alembic commands ###
