"""create gene and protein tables

Revision ID: 4dcf653fd0ba
Revises: 
Create Date: 2026-07-16 21:16:42.229146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dcf653fd0ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gene',
    sa.Column('gene_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('chromosome', sa.String(length=10), nullable=True),
    sa.Column('start_position', sa.BigInteger(), nullable=True),
    sa.Column('end_position', sa.BigInteger(), nullable=True),
    sa.Column('strand', sa.String(length=1), nullable=True),
    sa.Column('subtype_tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('ncbi_gene_id', sa.String(length=20), nullable=True),
    sa.Column('ensembl_id', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('gene_id')
    )
    with op.batch_alter_table('gene', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gene_symbol'), ['symbol'], unique=True)

    op.create_table('protein',
    sa.Column('protein_id', sa.Integer(), nullable=False),
    sa.Column('gene_id', sa.Integer(), nullable=False),
    sa.Column('uniprot_id', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('sequence_length', sa.Integer(), nullable=True),
    sa.Column('function_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['gene_id'], ['gene.gene_id'], ),
    sa.PrimaryKeyConstraint('protein_id')
    )
    with op.batch_alter_table('protein', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_protein_uniprot_id'), ['uniprot_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('protein', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_protein_uniprot_id'))

    op.drop_table('protein')
    with op.batch_alter_table('gene', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gene_symbol'))

    op.drop_table('gene')
    # ### end Alembic commands ###
