"""add drug table

Revision ID: 4e4961e4dfca
Revises: 52d65f997dd0
Create Date: 2026-07-18 13:01:04.227396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e4961e4dfca'
down_revision = '52d65f997dd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drug',
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('gene_id', sa.Integer(), nullable=False),
    sa.Column('drug_name', sa.String(length=200), nullable=False),
    sa.Column('interaction_type', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['gene_id'], ['gene.gene_id'], ),
    sa.PrimaryKeyConstraint('drug_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drug')
    # ### end Alembic commands ###
