"""add publication table

Revision ID: 52d65f997dd0
Revises: f2a8ef5179a0
Create Date: 2026-07-18 11:45:51.715796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52d65f997dd0'
down_revision = 'f2a8ef5179a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publication',
    sa.Column('pub_id', sa.Integer(), nullable=False),
    sa.Column('gene_id', sa.Integer(), nullable=False),
    sa.Column('pmid', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('authors', sa.String(length=500), nullable=True),
    sa.Column('journal', sa.String(length=200), nullable=True),
    sa.Column('pub_year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gene_id'], ['gene.gene_id'], ),
    sa.PrimaryKeyConstraint('pub_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publication')
    # ### end Alembic commands ###
