"""add tcga_stats table

Revision ID: f656acbd49f2
Revises: 3d14da4ef29c
Create Date: 2026-07-18 10:29:57.428308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f656acbd49f2'
down_revision = '3d14da4ef29c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tcga_stats',
    sa.Column('stat_id', sa.Integer(), nullable=False),
    sa.Column('gene_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=True),
    sa.Column('mutated_cases', sa.Integer(), nullable=True),
    sa.Column('total_cases', sa.Integer(), nullable=True),
    sa.Column('frequency_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['gene_id'], ['gene.gene_id'], ),
    sa.PrimaryKeyConstraint('stat_id')
    )
    with op.batch_alter_table('tcga_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tcga_stats_gene_id'), ['gene_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tcga_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tcga_stats_gene_id'))

    op.drop_table('tcga_stats')
    # ### end Alembic commands ###
